---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: app
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 5h"
    keel.sh/approvals: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          imagePullPolicy: Always
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Asia/Chongqing
          ports:
            - containerPort: 8989
              protocol: TCP
          resources:
            requests:
              cpu: "400m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /vault
              name: vault
            - mountPath: /tv
              name: tv
            - mountPath: /archive
              name: archive
            - mountPath: /downloads
              name: downloads
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: downloads
          hostPath:
            path: /home/kid/downloads
            type: Directory
        - name: vault
          hostPath:
            path: /mnt/vault
            type: Directory
        - name: archive
          hostPath:
            path: /mnt/archive
            type: Directory
        - name: tv
          hostPath:
            path: /mnt/tv
            type: Directory
