apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- system-upgrade
- traefik
- keel
- jellyfin
- sonarr
- radarr
- bazarr
- prowlarr
- qbittorrent
- miniflux
- homeassistant

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
