apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniflux

resources:
- namespace.yml
- pvc.yml
- deployment.yml
- service.yml
- ../base

secretGenerator:
- name: postgres-secret
  envs:
  - .env
- name: miniflux-secret
  envs:
  - .env

configMapGenerator:
- name: app-config
  literals:
  - APP_SUBDOMAIN=rss
- name: nextflux-app-config
  literals:
  - APP_SUBDOMAIN=flux

replacements:
- source:
    kind: ConfigMap
    name: app-config
    fieldPath: data.APP_SUBDOMAIN
  targets:
  - select:
      kind: Ingress
      name: ingress
    fieldPaths:
    - spec.rules.0.host
    - spec.rules.1.host
    options:
      delimiter: "."
      index: 0
- source:
    kind: ConfigMap
    name: nextflux-app-config
    fieldPath: data.APP_SUBDOMAIN
  targets:
  - select:
      kind: Ingress
      name: ingress
    fieldPaths:
    - spec.rules.2.host
    - spec.rules.3.host
    options:
      delimiter: "."
      index: 0
- source:
    kind: ConfigMap
    name: domain-config
    fieldPath: data.LAN_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: ingress
    fieldPaths:
    - spec.rules.0.host
    - spec.rules.2.host
    options:
      delimiter: "."
      index: 1
- source:
    kind: ConfigMap
    name: domain-config
    fieldPath: data.WAN_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: ingress
    fieldPaths:
    - spec.rules.1.host
    - spec.rules.3.host
    options:
      delimiter: "."
      index: 1

patches:
- target:
    kind: Ingress
    name: ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/backend/service/port/number
      value: 80
    - op: replace
      path: /spec/rules/1/http/paths/0/backend/service/port/number
      value: 80
    - op: add
      path: /spec/rules/-
      value:
        host: dummy-nextflux-lan
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: service
                  port:
                    number: 8300
    - op: add
      path: /spec/rules/-
      value:
        host: dummy-nextflux-wan
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: service
                  port:
                    number: 8300

labels:
- includeSelectors: true
  pairs:
    app: miniflux
    app.kubernetes.io/managed-by: kustomize
