---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: miniflux
  ports:
    - name: miniflux
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: nextflux
      protocol: TCP
      port: 8300
      targetPort: 3000
