# Default configuration
default_config:

# HTTP configuration for reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.42.0.0/16 # k3s default pod CIDR
    - 10.43.0.0/16 # k3s default service CIDR
    - 127.0.0.1
    - ::1
