apiVersion: v1
kind: Service
metadata:
  labels:
    app: homarr
  name: service
spec:
  ports:
    - name: http
      port: 7575
      protocol: TCP
      targetPort: 7575
  selector:
    app: homarr
  type: ClusterIP
