apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: app
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 5h"
    keel.sh/approvals: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - image: jellyfin/jellyfin:latest
          name: jellyfin
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 7359
              protocol: UDP
          resources:
            requests:
              cpu: "1"
              memory: 256Mi
            limits:
              cpu: "6"
              memory: 1Gi
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /cache
              name: cache
            - mountPath: /archive
              name: archive
            - mountPath: /vault
              name: vault
            - mountPath: /tv
              name: tv
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
        - name: cache
          persistentVolumeClaim:
            claimName: cache
        - name: archive
          hostPath:
            path: /mnt/archive
            type: Directory
        - name: vault
          hostPath:
            path: /mnt/vault
            type: Directory
        - name: tv
          hostPath:
            path: /mnt/tv
            type: Directory
